### ISSUE TITLE
Resize & scroll

### ISSUE THREAD

**Issue by RCollins13** [JakeConway/TBRdenWebApp#4]
Scrolling right or left after resizing viewport appears to erase all tracks

**Comment by RCollins13** [comment]
This effect only happens once you scroll to the border of the current view window. After that, all tracks are erased (including the coordinate ruler at the top of the view window)

**Comment by JakeConway** [comment]
this probably has to do with issue 2, where if we hit a region where we have absolutely nothing, it erases everything because there is nothing to rerender
